vim.g.coq_settings = {
   auto_start = "shut-up",
   display = {
      ghost_text = {
         context = { " ⟨ ", " ⟩ " },
      },
      preview = {
         positions = { west = 1, east = 2, north = 3, south = 4 },
      },
      icons = {
         mappings = {
            Boolean = "",
            Character = "",
            Class = "ﴯ",
            Color = "",
            Constant = "",
            Constructor = "",
            Enum = "",
            EnumMember = "",
            Event = "",
            Field = "",
            File = "",
            Folder = "",
            Function = "λ",
            Interface = "",
            Keyword = "",
            Method = "",
            Module = "",
            Number = "",
            Operator = "Ψ",
            Parameter = "",
            Property = "ﭬ",
            Reference = "",
            Snippet = "",
            String = "",
            Struct = "ﯟ",
            Text = "",
            TypeParameter = "",
            Unit = "",
            Value = "",
            Variable = "α",
         },
      },
      pum = {
         kind_context = { "⟨", "⟩" },
         source_context = { "⌈", "⌋" },
      },
   },
}
